### ISSUE TITLE
additional installations needed for geneformer notebook

### ISSUE THREAD

**Issue by vjcitn** [microsoft/zero-shot-scfoundation#4]
scib
colorlog
scgpt
wcwidth
PyComplexHeatmap

and if we just install them with pip, version incompatibilities lead to

ModuleNotFoundError: No module named 'matplotlib.pylab'

I will try to find compatible version values ... is this common with python?

**Comment by vjcitn** [comment]
it seems fixable; this fork has a revised env file to incorporate the missing packages, but then see https://github.com/vjcitn/zero-shot-scfoundation/issues/1 where the tokenizer can't complete its output task.

**Comment by kzkedzierska** [comment]
Hi @vjcitn, thank you so much for your comment! I have fixed this now in #6, and added the docker images that might come in handy with reproducing the workflow.
